"""NOTICE file rendering."""

from __future__ import annotations

from pathlib import Path

from ai_plugin_vendor_tool.config import PluginMeta, Source
from ai_plugin_vendor_tool.lock import LockData

_BAR = "-" * 79


def render_notice(meta: PluginMeta, sources: list[Source], lock: LockData) -> str:
    header = (
        f"{meta.name}\n"
        f"Copyright (c) {meta.author}\n\n"
        f"Licensed under the {meta.license} License.\n\n"
        f"{_BAR}\n"
        "This product includes vendored skills from third-party projects. The list\n"
        "below is managed by ai-plugin-vendor-tool using\n"
        "vendor/vendored-skills.toml as the source of truth. Do not edit this file\n"
        "manually — re-run the sync tool.\n"
        f"{_BAR}\n"
    )
    blocks: list[str] = []
    for s in sources:
        entry = lock.get(s.name)
        sha = entry["commit"] if entry is not None else "(unknown)"
        skills = entry["skills"] if entry is not None else []
        url = s.attribution_url or f"https://github.com/{s.repo}"
        skills_fmt = ", ".join(skills) if skills else "(none)"
        blocks.append(
            f"\n## {s.name}\n\n"
            f"Source:       {url}\n"
            f"License:      {s.license}\n"
            f"Attribution:  {s.attribution}\n"
            f"Ref:          {s.ref} (commit {sha})\n"
            f"Skills ({len(skills)}): {skills_fmt}\n\n"
            f"Skills listed above are verbatim copies redistributed under the\n"
            f"{s.license} license with attribution as required.\n"
        )
    return header + "".join(blocks)


def write_notice(path: Path, meta: PluginMeta, sources: list[Source], lock: LockData) -> None:
    path.write_text(render_notice(meta, sources, lock))
